version: '3.9'
services:
  maria_rdb:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: daangn
      MYSQL_DATABASE: ourapt
      MYSQL_USER: daangn
      MYSQL_PASSWORD: daangn
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  common_api_server:
    build: ./common_api_server
    ports:
      - 8080:8080
    volumes:
      - ./common_api_server:/usr/src/ourapt_api_server
    environment:
      - RDB_HOST=maria_rdb:3306
      - KARROT_APP_ID=6e6ba05f78534202aa4afe21daf1c825
      - KARROT_APP_SECRET=8c22a99c27ef45f6a18e7c39b87c6568
      - KARROT_API_KEY=FKT4tn5arLHR0ontSGNarIayhldHf0t4fVi4cVG0IUI=

  # react_view_render_server:

volumes:
  mysql_data:
