# compose file for only local development environment
version: '3.9'
services:
  maria_rdb:
    image: mariadb:10.6.4
    environment:
      MYSQL_ROOT_PASSWORD: daangn
      MYSQL_DATABASE: ourapt
      MYSQL_USER: daangn
      MYSQL_PASSWORD: daangn
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  common_api_server:
    build:
      context: ./common_api_server
      dockerfile: Dockerfile.dev
    ports:
      - 8080:5000
    volumes:
      - ./common_api_server:/usr/src/ourapt_api_server
    env_file:
      - ./common_api_server/.env

  # react_view_render_server:

volumes:
  mysql_data:
