server:
  tomcat:
    accesslog:
      enabled: true
      buffered: false
      directory: /dev
      prefix: stdout
      file-date-format:
      suffix:
spring:
  application:
    name: ourapt_api_server
  # web:
  #   resources:
  #     static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://${RDB_HOST}/ourapt
    driver-class-name: org.mariadb.jdbc.Driver
    username: daangn
    password: daangn
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

karrot:
  api:
    app-id: ${KARROT_APP_ID}
    app-secret: ${KARROT_APP_SECRET}
    base-url: ${KARROT_BASE_URL}
    api-key: ${KARROT_API_KEY}
