server:
  port: 5000
  tomcat:
    accesslog:
      enabled: true
      buffered: false
      directory: /dev
      prefix: stdout
      file-date-format:
      suffix:
ring:
  application:
    name: ourapt_api_server
  # web:
  #   resources:
  #     static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://${RDB_HOST}/ourapt
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

karrot:
  api:
    app-id: ${KARROT_APP_ID}
    app-secret: ${KARROT_APP_SECRET}
    api-key: ${KARROT_API_KEY}
    open-api-base-url: ${KARROT_OPEN_API_BASE_URL}
    o-api-base-url: ${KARROT_O_API_BASE_URL}
