server:
  port: 5000
spring:
  application:
    name: ourapt_api_server
  # web:
  #   resources:
  #     static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://${RDB_HOST}/ourapt?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        connection:
          CharSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  thymeleaf:
    prefix: classpath:/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    order: 0

sentry:
  dsn: https://b96910f5fc0348c78f45a911b197f86e@o1091881.ingest.sentry.io/6109524
  traces-sample-rate: 0.3
  environment: alpha

karrot:
  api:
    app-id: ${KARROT_APP_ID}
    app-secret: ${KARROT_APP_SECRET}
    api-key: ${KARROT_API_KEY}
    open-api-base-url: ${KARROT_OPEN_API_BASE_URL}
    o-api-base-url: ${KARROT_O_API_BASE_URL}
