server:
  port: 8080
#  tomcat:
#    accesslog:
#      enabled: true
#      buffered: false
#      directory: /dev
#      prefix: stdout
#      file-date-format:
#      suffix:
logging:
  level:
    org:
      springframework:
        cache: TRACE
spring:
  application:
    name: ourapt_api_server
  datasource:
    url: jdbc:mariadb://${RDB_HOST}/ourapt?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        connection:
          CharSet: UTF-8
          characterEncoding: TF-8
          useUnicode: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    prefix: classpath:/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: false
    order: 0

sentry:
  dsn: https://b96910f5fc0348c78f45a911b197f86e@o1091881.ingest.sentry.io/6109524
  traces-sample-rate: 0.3
  environment: dev

karrot:
  api:
    app-id: ${KARROT_APP_ID}
    app-secret: ${KARROT_APP_SECRET}
    api-key: ${KARROT_API_KEY}
    open-api-base-url: ${KARROT_OPEN_API_BASE_URL}
    o-api-base-url: ${KARROT_O_API_BASE_URL}
