# This is profile for alpha & local
# This setting apply for both local server and alpha server.
server:
  port: 5000
spring:
  application:
    name: ourapt_api_server
  # web:
  #   resources:
  #     static-locations: classpath:/static/
  datasource:
    url: jdbc:mariadb://${RDB_HOST}/ourapt?useUnicode=true&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: false
        connection:
          CharSet: UTF-8
          characterEncoding: UTF-8
          useUnicode: true
    hibernate:
      ddl-auto: validate
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false

karrot:
  api:
    app-id: ${KARROT_APP_ID}
    app-secret: ${KARROT_APP_SECRET}
    api-key: ${KARROT_API_KEY}
    open-api-base-url: ${KARROT_OPEN_API_BASE_URL}
    o-api-base-url: ${KARROT_O_API_BASE_URL}
